Add util struct to build renderable elements from a log line (#4)
* .

* add a util struct to build elements for a log line

* cleanup

diff --git a/script/build b/script/build
--- a/script/build
+++ b/script/build
@@ -1,3 +1,10 @@
 #!/bin/bash
 
+if ! command -v wasm-pack &> /dev/null
+then
+    echo "wasm-pack could not be found"
+    echo "get it from: https://rustwasm.github.io/wasm-pack/installer/"
+    exit 1
+fi
+
 wasm-pack build --target web --out-dir web/dist/
